# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bec04dbb2748d9484125ebc5d5a83ff56eabde6c3ebe12fa8da9effc08075e995421e1676b7ccf06ea7f4637ff9e78245e2ebab913bdd25ab91afbd0b54e8e4a

test:
  secret_key_base: 4d921570bda9e327da84f8f05e98c5cf90014d776fc91db48b871923dca86c09ece12105792637bd975ebb1bebbd6a0b28f720c9777bad71b81572258171d7cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
